<?php

/**
 * @file
 * Contains usuario_wdls.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Connection;
use Symfony\Component\HttpFoundation;

function _usuario_wdls_login_submit(&$form, FormStateInterface $form_state) {
	$database = \Drupal::database();
	$database->insert('log_users')
		->fields([
			'fecha' => time(),
			'ip' =>  \Drupal::request()->getClientIp(),
			'uid' => $form_state->get('uid'),
			'tipo_log' => 'login',
		])
		->execute();
	drupal_set_message('Registro de login guardado en la BD');
}

function _usuario_wdls_register_submit(&$form, FormStateInterface $form_state) {
	$database = \Drupal::database();
	$database->insert('log_users')
		->fields([
			'fecha' => time(),
			'ip' =>  \Drupal::request()->getClientIp(),
			'uid' => $form_state->getValue('uid'),
			'tipo_log' => 'registro',
		])
		->execute();
	drupal_set_message('Registro de registro guardado en la BD');
}

/**
 * Implements hook_form_user_login_form_alter().
 */
function usuario_wdls_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  	$form['#submit'][] = '_usuario_wdls_login_submit';
}

/**
 * Implements hook_form_user_register_form_alter().
 */
function usuario_wdls_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  	$form['actions']['submit']['#submit'][] = '_usuario_wdls_register_submit';
}

/**
 * Implements hook_help().
 */
function usuario_wdls_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the usuario_wdls module.
    case 'help.page.usuario_wdls':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo para prueba de serempre de William David Leon Sacristan') . '</p>';
      return $output;

    default:
  }
}
